---

stages:
- stage: Build

  jobs:
  - job: "Build containers for $(ARCH)"
    pool:
      vmImage: "ubuntu-16.04"
    strategy:
      matrix:
        armhf:
          arch: armhf
        arm64:
          arch: arm64
        i386:
          arch: i386
        amd64:
          arch: amd64
    steps:
    - displayName: Register QEMU wrappers
      script: docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - checkout: self
      fetchDepth: 1
    - displayName: Build container
      script: |
        docker build -t "pqclean/ci-container:$(arch)" --build-arg "ARCH=$(arch)" debian-buster
