---
pool:
  vmImage: 'ubuntu-16.04'

stages:
- stage: Build

  jobs:
  - job: "Build containers for $(ARCH)"
    strategy:
      matrix:
        armhf:
          ARCH=armhf
        arm64:
          ARCH=arm64
        i386:
          ARCH=i386
        amd64:
          ARCH=amd64
    steps:
    - displayName: Register QEMU wrappers
      script: docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - displayName: Build container
      script: |
        docker build -t "pqclean/ci-container:$(ARCH)" --build-arg "ARCH=$(ARCH)" debian-buster

##test:
##  #  - script: |
##  #      docker login --username $(dockerUser) -p $(dockerPassword)
##  #      docker push "pqclean/ci-container:${{ paramters.arch }}"
